### ISSUE TITLE
Error: Cannot destructure property 'email' of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Nashati** [tool3/bump#9]
Hi,
I keep getting this error while using this action:

`Error: Cannot destructure property 'email' of 'undefined' or 'null'.`

This is my workflow:

```
on: [workflow_dispatch]
name: Build Test and Publish
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUBTOKEN }}" > ~/.npmrc
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUBTOKEN }}" > ~/.npmrc
      - run: npm ci
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - uses: tool3/bump@v.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          unrelated: true
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUBTOKEN}}

```

Any help is appreciated.

**Comment by tool3** [comment]
hey @Nashati I see you are using `tool3/bump@v.1.2` - can you try `tool3/bump@master` and see if it resolves it ?

**Comment by Nashati** [comment]
Hey @tool3, 
I already try it, I actually started with 'master' and it didn't work.

**Comment by tool3** [comment]
@Nashati I stand corrected! 
released this as `v1.1.0` but you are free to use `tool3/bump@master` as well of course.
https://github.com/tool3/bump/releases/tag/v1.1.0

the problem was that I was using the `pusher` property on the github context response object instead of `committer`.

**Comment by Nashati** [comment]
Hi, 
I tried the newer version, now I get this:
```YAML
Run tool3/bump@v1.1.0
  with:
    github_token: ***
    unrelated: true
    branch: master
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Error: Cannot destructure property `message` of 'undefined' or 'null'.
```

**Comment by tool3** [comment]
@Nashati that's strange. I use github's context to get user information from their API using your `GITHUB_TOKEN`.

this actually means that there is no `committer` object on the response object.

are you running this against a valid git repo that has `master`? 

also in this example I don't see your usage of `github_token: ${{ secrets.GITHUB_TOKEN }}`

**Comment by Nashati** [comment]
Yes, I am running against a valid repo with `master` branch.

**Comment by tool3** [comment]
@Nashati I don't have much to go by...but it seems that if the `committer` object didn't return on the response object, it might mean that the committer is not a  github user ?  could that be ? 

I'm afraid that the next step would be to create a debug version of this action to print the github context in your action and inspect it.

**Comment by tool3** [comment]
@Nashati please run with `tool3/bump@debug` and paste the output from the action.

**Comment by Nashati** [comment]
Here is the output, note that I hided the organization name and the repository name: 
```YAML
Run tool3/bump@debug
  with:
    github_token: ***
    unrelated: true
    branch: master
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Context {
  payload: {
    inputs: null,
    organization: {
      avatar_url: 'https://avatars.githubusercontent.com/u/17124134?v=4',
      description: '',
      events_url: 'https://api.github.com/orgs/<OrganizationName>/events',
      hooks_url: 'https://api.github.com/orgs/<OrganizationName>/hooks',
      id: 17124134,
      issues_url: 'https://api.github.com/orgs/<OrganizationName>/issues',
      login: '<OrganizationName>',
      members_url: 'https://api.github.com/orgs/<OrganizationName>/members{/member}',
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjE3MTI0MTM0',
      public_members_url: 'https://api.github.com/orgs/<OrganizationName>/public_members{/member}',
      repos_url: 'https://api.github.com/orgs/<OrganizationName>/repos',
      url: 'https://api.github.com/orgs/<OrganizationName>'
    },
    ref: 'refs/heads/master',
    repository: {
      archive_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/{archive_format}{/ref}',
      archived: false,
      assignees_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/assignees{/user}',
      blobs_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/git/blobs{/sha}',
      branches_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/branches{/branch}',
      clone_url: 'https://github.com/<OrganizationName>/<RepositoryName>.git',
      collaborators_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/collaborators{/collaborator}',
      comments_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/comments{/number}',
      commits_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/commits{/sha}',
      compare_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/compare/{base}...{head}',
      contents_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/contents/{+path}',
      contributors_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/contributors',
      created_at: '2020-09-10T11:14:28Z',
      default_branch: 'master',
      deployments_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/deployments',
      description: null,
      disabled: false,
      downloads_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/downloads',
      events_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/events',
      fork: false,
      forks: 0,
      forks_count: 0,
      forks_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/forks',
      full_name: '<OrganizationName>/<RepositoryName>',
      git_commits_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/git/commits{/sha}',
      git_refs_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/git/refs{/sha}',
      git_tags_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/git/tags{/sha}',
      git_url: 'git://github.com/<OrganizationName>/<RepositoryName>.git',
      has_downloads: true,
      has_issues: true,
      has_pages: false,
      has_projects: true,
      has_wiki: true,
      homepage: null,
      hooks_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/hooks',
      html_url: 'https://github.com/<OrganizationName>/<RepositoryName>',
      id: 294386918,
      issue_comment_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/issues/comments{/number}',
      issue_events_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/issues/events{/number}',
      issues_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/issues{/number}',
      keys_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/keys{/key_id}',
      labels_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/labels{/name}',
      language: 'JavaScript',
      languages_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/languages',
      license: null,
      merges_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/merges',
      milestones_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/milestones{/number}',
      mirror_url: null,
      name: '<RepositoryName>',
      node_id: 'MDEwOlJlcG9zaXRvcnkyOTQzODY5MTg=',
      notifications_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/notifications{?since,all,participating}',
      open_issues: 6,
      open_issues_count: 6,
      owner: [Object],
      private: true,
      pulls_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/pulls{/number}',
      pushed_at: '2021-02-08T13:50:57Z',
      releases_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/releases{/id}',
      size: 623,
      ssh_url: 'git@github.com:<OrganizationName>/<RepositoryName>.git',
      stargazers_count: 0,
      stargazers_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/stargazers',
      statuses_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/statuses/{sha}',
      subscribers_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/subscribers',
      subscription_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/subscription',
      svn_url: 'https://github.com/<OrganizationName>/<RepositoryName>',
      tags_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/tags',
      teams_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/teams',
      trees_url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>/git/trees{/sha}',
      updated_at: '2021-02-08T13:51:00Z',
      url: 'https://api.github.com/repos/<OrganizationName>/<RepositoryName>',
      watchers: 0,
      watchers_count: 0
    },
    sender: {
      avatar_url: 'https://avatars.githubusercontent.com/u/29517209?v=4',
      events_url: 'https://api.github.com/users/Nashati/events{/privacy}',
      followers_url: 'https://api.github.com/users/Nashati/followers',
      following_url: 'https://api.github.com/users/Nashati/following{/other_user}',
      gists_url: 'https://api.github.com/users/Nashati/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/Nashati',
      id: 29517209,
      login: 'Nashati',
      node_id: 'MDQ6VXNlcjI5NTE3MjA5',
      organizations_url: 'https://api.github.com/users/Nashati/orgs',
      received_events_url: 'https://api.github.com/users/Nashati/received_events',
      repos_url: 'https://api.github.com/users/Nashati/repos',
      site_admin: false,
      starred_url: 'https://api.github.com/users/Nashati/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Nashati/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/Nashati'
    },
    workflow: '.github/workflows/build-test-release-workflow.yml'
  },
  eventName: 'workflow_dispatch',
  sha: '0658e653216fd501b15656d78b2aae68dfbd8c3e',
  ref: 'refs/heads/master',
  workflow: 'Build Test and Publish',
  action: 'tool3bump',
  actor: 'Nashati'
}
```

**Comment by tool3** [comment]
@Nashati as you can see, for some reason the response object doesn't contain any `committer` object, and therefore `bump` fails miserably.

I have modified the `debug` version to include a helpful error message.

finally, to resolve your issue please provide `username` and `email` through the workflow file, as such:
```yaml
- uses: tool3/bump@debug
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        branch: 'debug'
        username: 'Nashati'
        email: 'some@email.com'
```

this should resolve the issue and allow `bump` to run successfully.
I'll await your response and merge these back to master.

**Comment by Nashati** [comment]
with `username` it didn't work, I used `user` and still getting an error:
```YAML
Run tool3/bump@debug
  with:
    github_token: ***
    branch: debug
    unrelated: true
    user: Nashati
    email: nashat.ib@gmail.com
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Error: Cannot read property 'committer' of undefined
```

**Comment by tool3** [comment]
@Nashati I now realize that the problem is that there is no `head_commit` object **at all**...
I have updated it one last time,
please rerun your last example again (with `user`)

**Comment by Nashati** [comment]
```YAML
Run tool3/bump@debug
  with:
    github_token: ***
    unrelated: true
    user: Nashati
    email: nashat.ib@gmail.com
    branch: master
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Error: message is not defined
```

**Comment by tool3** [comment]
@Nashati  I am such a mess !! please re-run I created yet another debug version!

**Comment by Nashati** [comment]
Still failing...
```YAML
Run tool3/bump@debug
  with:
    github_token: ***
    unrelated: true
    user: Nashati
    email: nashat.ib@gmail.com
    branch: master
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Error: Cannot read property 'includes' of undefined
```

**Comment by tool3** [comment]
@Nashati sorry, I have very little ways to test the code before releasing a version, that's why all the back and forth.
released another one, please check.

**Comment by Nashati** [comment]
Working now... thanks

**Comment by Nashati** [comment]
@tool3 
Can you please release a new version with all the fixes?

**Comment by tool3** [comment]
@Nashati done
https://github.com/tool3/bump/releases/tag/v1.1.1
